### ISSUE TITLE
Unlocalize pk in delete_selected_confirmation.html template

### ISSUE THREAD

**Issue by poptosic** [stephenmcd/grappelli-safe#15]
Object's pk should be unlocalized in delete_selected_confirmation.html because it raises an error when localization is turned on, for numbers above 999 when there is a thousand separator. I think this was corrected in django-grapelli.

**Comment by dsanders11** [comment]
Just an FYI, this issue can be closed, it was fixed in f2a1b8bf8e2ee8f695c09ca0807bc1c8de770128.

**Comment by stephenmcd** [comment]
Ace, thanks!
