### ISSUE TITLE
tiny_mce image plugin 

### ISSUE THREAD

**Issue by haganf** [stephenmcd/grappelli-safe#45]
Mezzanine ver 3.1.10 and grappelli-safe ver 0.3.13

From a fresh install of mezzanine, i'm running into minor annoyance with tiny_mce's popup insert/edit image view.  There is just a blank gray square where i think an icon should appear.
![screen shot 2015-01-13 at 9 36 38 am](https://cloud.githubusercontent.com/assets/4603500/5724277/c9be0710-9b07-11e4-9c4a-12edfb714cef.png)

I think this might be missing some css, perhaps 'advimage.css' from the admin's base.html.. I'd love to fix this as we need the icon for usablility and i'd rather keep this version of tiny_mce and avoid more work.

Any idea's?

thanks,

-hagan

**Comment by stephenmcd** [comment]
Not sure what's wrong but it's definitely broken - if you can work out the fix that'd be awesome, thank you.

**Comment by haganf** [comment]
This might be a hacky fix, i'm not sure what icon's where are missing and how.. But a quick modification and included paper clip icon seemed to give me this:

![screen shot 2015-01-14 at 10 01 04 am](https://cloud.githubusercontent.com/assets/4603500/5743096/4a03a084-9bd4-11e4-935d-9dd23796ddfa.png)

**Comment by stephenmcd** [comment]
Resolved long ago when we changed the theme.
