### ISSUE TITLE
password_reset_email.html accesses user.username which isn't guaranteed to exist

### ISSUE THREAD

**Issue by gavinwahl** [stephenmcd/grappelli-safe#47]
The user model contract has `get_username`, not `username`. The template should use that instead. Alternatively, I'm not sure why this template is even overridden by grappelli-safe. It looks like it's the same as the one provided by django. This bug could also be fixed by just deleting the template from grappelli-safe.

**Comment by stephenmcd** [comment]
Nice pickup, thanks Gavin.
