### ISSUE TITLE
Incorrect "Cancel" link on delete_selected_confirmation.html

### ISSUE THREAD

**Issue by stefanistrate** [stephenmcd/grappelli-safe#72]
When I select a few objects in admin mode and click "Delete selected objects", I am presented with 2 options:
1. "Yes, I'm sure", which brings me back to the page where I selected the objects.
2. "Cancel", which sends me one step back in the page hierarchy: https://github.com/stephenmcd/grappelli-safe/blob/master/grappelli_safe/templates/admin/delete_selected_confirmation.html#L47

I would expect (2) to send me to the same page as (1) after completing the operation. Looking at the latest Django template, this seems to be working properly by using the "window.history.back()" event: https://github.com/django/django/blob/stable/1.9.x/django/contrib/admin/templates/admin/delete_selected_confirmation.html#L45 Would you consider fixing this in "grappelli-safe"?

**Comment by stephenmcd** [comment]
Thanks for the report, it's fixed now.
