### ISSUE TITLE
localized datetime format in object history seems to be incorrect

### ISSUE THREAD

**Issue by christianwgd** [stephenmcd/grappelli-safe#82]
for example in german localization this is rendered as:
"Dinachm.CEST1464117217MaithMai+0200RMainachm.CEST"

I suppose this is because the action_time field is treated as a translated string:
<th scope="row">{{ action.action_time|date:**_("DATETIME_FORMAT")** }}</th>

When i change that to simple "DATETIME_FORMAT" i get the correct german localized datetime string:
"24. Mai 2016 21:13"

**Comment by stephenmcd** [comment]
Cool! How about a PR with your fix?

**Comment by christianwgd** [comment]
No problem, will do it at the weekend..

Christian

**Comment by stephenmcd** [comment]
#83
