### ISSUE TITLE
Wheel file out of sync with source package

### ISSUE THREAD

**Issue by stefanistrate** [stephenmcd/grappelli-safe#87]
I've been investigating why the password reset mechanism doesn't work properly with Mezzanine and I've discovered that the *.whl and the *.tar.gz files from https://pypi.python.org/pypi/grappelli_safe/0.4.6 contain different templates under "templates/registration". Any idea what is going on? After installing the *.tar.gz file via pip, the password reset seems to be working.

**Comment by stephenmcd** [comment]
Just pushed 0.4.7 which should resolve this.
