### ISSUE TITLE
Two deprecated template tags should be removed

### ISSUE THREAD

**Issue by xuchen81** [stephenmcd/grappelli-safe#88]
pip install will install two files that are not in the code:
`/Python/2.7/site-packages/grappelli_safe/templates/registration/logged_out.html`
`/Python/2.7/site-packages/grappelli_safe/templates/registration/password_reset_email.html`

However, if I pip install directly from master branch, those two files will not be created, so there must be something broken when the package was put on PyPi.

`future` and `crispy_forms_tags` should be removed from the following templates.
```
Invalid template /local/lib/python2.7/site-packages/grappelli_safe/templates/registration/password_reset_email.html: 'future' is not a registered tag library.
```
```
Invalid template /local/lib/python2.7/site-packages/rest_framework/templates/rest_framework/filters/django_filter_crispyforms.html: 'crispy_forms_tags' is not a registered tag library.
```

**Comment by stephenmcd** [comment]
The former was done some time ago - the latter is a different library than this one.
