### ISSUE TITLE
Django 1.11.11 - broken "Select All" checkbox

### ISSUE THREAD

**Issue by kwasielew** [stephenmcd/grappelli-safe#91]
Hey,
After upgrading to Django 1.11 our "_Select All_" checkbox is not selecting all items on the page.
I've spend some time debugging the issue and it looks like it's related to https://github.com/stephenmcd/grappelli-safe/commit/4c90351343a241de7452f36a51cef7fa056fcd0d
which seems to be out of date in newer Django.
From Django 1.9 **actions.js** file looks like: https://github.com/django/django/blob/stable/1.11.x/django/contrib/admin/static/admin/js/actions.js
and when using this code it works again.
If you want I can prepare pull request which deletes **actions.js** (I think it is not needed anymore?)
Thanks

**Comment by stephenmcd** [comment]
> If you want I can prepare pull request

That'd be great, thank you.

**Comment by kwasielew** [comment]
Hey @stephenmcd 
The pull request is ready here: https://github.com/stephenmcd/grappelli-safe/pull/92

**Comment by stephenmcd** [comment]
Unable to reproduce as described in the PR.
