### ISSUE TITLE
Tags for versions > 0.4.5?

### ISSUE THREAD

**Issue by edwargix** [stephenmcd/grappelli-safe#95]
The following versions are available on PyPi, but this repo doesn't have tags for any of them. Any chance they can be added?

- 0.4.6: ac9d2cf
- 0.4.7: 2562c21
- 0.5.0: f2d25c6
- 0.5.1: a0788c6
- 0.5.2: 035e210

**Comment by jerivas** [comment]
Thanks!

Tags have been added :)
